fastlane_version "2.136.0"

default_platform :ios

platform :ios do

    before_all do

        ENV["SLACK_URL"] = "https://hooks.slack.com/services" + "/TH0QEA8U9/BNZN41NN7/dbYCOhlavcLeauUL777XPVoG"
        ensure_git_status_clean

    end

    lane :beta do |options|

        ensure_git_branch( branch: 'develop|hotfix' )

        configuration = ""

        #parsing options
	#increment_version_number does not work properly with MARKETING_VERSION.
	#increment_version_number_in_xcodeproj from fastlane versioning plugin is user instead.

  	increment_build_number
    if options[:patch]
        version_number = increment_version_number_in_xcodeproj(bump_type: "patch")
    elsif options[:minor]
        version_number = increment_version_number_in_xcodeproj(bump_type: "minor")
	  end

    if options[:adhoc]
        configuration = "AdHoc"
    else
        configuration = "Release"
    end

    ##select adhoc provisioning profile
    match(
        app_identifier: "com.fantasyapp.iosclient,com.fantasyapp.iosclient.FantasyAppRichPush",
	git_url: "https://github.com/fantasyapptech/ios-certificates",
        type: "adhoc",
        readonly: true
    )

    ##building ipa
    xcode_select("/Applications/Xcode 11.app")
    gym(scheme: "FantasyApp",
        configuration: configuration,
        include_bitcode: false,
        export_options: {
            method: "ad-hoc",
            compileBitcode: false
        }
    )

    ###uploading to firebase
    firebase_app_distribution(
        app: "1:730700349275:ios:b23a8045cf4a0fdc0f247e",
        groups: "Basic",
        release_notes: changelog_from_git_commits
    )

    ##cleaning up
    File.delete("../FantasyApp.ipa")
    File.delete("../FantasyApp.app.dSYM.zip")

    ##notifying testers
    slack( message: "New beta build is available. Check build details below or at your emails. \n\n*🛑 Please delete 💥 previous build from your device 📱 to avoid unexpected issues 😭*\n\n",

          use_webhook_configured_username_and_icon: true,
          payload: {
          'Version number' => get_version_number(target: "FantasyApp"),
          'Download Link' => "https://appdistribution.firebase.dev/app_distro/projects",
          },
          default_payloads: []
          )


    ###keeping record
    commit_version_bump(message: "Update version, build number")
    if version_number
        add_git_tag tag: version_number
    end

    #push_to_git_remote

  end

  lane :release do |options|

      ensure_git_branch( branch: 'master' )
      ##building ipa
      xcode_select("/Applications/Xcode 11.app")
      gym(scheme: "FantasyApp",
          configuration: "Release",
          export_method: "app-store",
          include_bitcode: true)


      if options[:username]
          username = options[:username]
      else
          username = "*"
      end

      upload_to_app_store(username: username,
			  skip_screenshots: true,
                          skip_app_version_update: true,
                          skip_metadata: true)
      ##cleaning up
      clean_build_artifacts

  end

  lane :refresh_dsym do |options|

    download_dsyms(version: "latest")
    upload_symbols_to_crashlytics
    clean_build_artifacts

  end

end
