fastlane_version "1.105.0"

default_platform :ios

platform :ios do
    
    before_all do
        ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
        ensure_git_status_clean
        
    end

    lane :beta do |options|
        
        ensure_git_branch( branch: 'develop|hotfix' )
        
        version_number = 0
        configuration = ""
        environmentName = ""
        
        #parsing options
        if options[:patch]
            version_number = increment_version_number(bump_type: "patch")
            else
            version_number = increment_version_number(bump_type: "minor")
        end
    
    if options[:adhoc]
        configuration = "AdHoc"
        environmentName = "Staging"
    else
        configuration = "Release"
        environmentName = "Production"
    end

    ##building ipa
    gym(scheme: "FantasyApp",
        configuration: configuration,
        include_bitcode: false,
        export_options: {
            method: "ad-hoc"
        }
    )
        
    ###uploading to crashlytics
    crashlytics(api_token: "e84ce1420f7f93176fb81a16a43f00b1cdbc00ff",
                build_secret: "23e218800f398f44a1b99535f0a9e70571f31c508860c4e4be496e02abcf6b7c",
                notes: changelog_from_git_commits,
                groups: "Basic")
    upload_symbols_to_crashlytics                    

    ##cleaning up
    File.delete("../FantasyApp.ipa")
    File.delete("../FantasyApp.app.dSYM.zip")
    
    ##notifying testers
    slack( message: "New beta build is available. Check build details below or at your emails. \n\n*🛑 Please delete 💥 previous build from your device 📱 to avoid unexpected issues 😭*\n\n",
          
          use_webhook_configured_username_and_icon: true,
          payload: {
          'Version number' => get_version_number,
          'Environment' => environmentName,
          'Download Link' => "https://apps.crashlytics.com/projects",
          },
          default_payloads: []
          )

          
    ###keeping record
    commit_version_bump(message: "Version bump to v#{version_number}")
    add_git_tag tag: version_number
    push_to_git_remote
    
  end

  lane :release do |options|
      
      ensure_git_branch( branch: 'master' )
      ##building ipa
      gym(scheme: "FantayApp",
          configuration: "Release",
          export_method: "app-store",
          include_bitcode: true)

      upload_to_app_store(skip_screenshots: true,
                          skip_app_version_update: true,
                          skip_metadata: true)
      ##cleaning up
      clean_build_artifacts
      
  end
  
  lane :refresh_dsym do |options|

    download_dsyms(version: "latest")
    upload_symbols_to_crashlytics(api_token: "e84ce1420f7f93176fb81a16a43f00b1cdbc00ff")
    clean_build_artifacts
     
  end
  
end
